services:
  ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "6060:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=node-01:9092
      - KAFKA_CLUSTERS_0_NAME=kraft
    extra_hosts:
      - node-01:172.16.0.2
      - node-02:172.16.0.3
      - node-03:172.16.0.4
      - node-04:172.16.0.5
      