[all]
node-01 ansible_host=node-01 kafka_broker_id=1
node-02 ansible_host=node-02 kafka_broker_id=2
node-03 ansible_host=node-03 kafka_broker_id=3
#node-04 ansible_host=node-04 kafka_broker_id=4

[zookeeper-nodes]
node-01 zookeeper_id=1
node-02 zookeeper_id=2
node-03 zookeeper_id=3